name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest
    container:
      image: adoptopenjdk/openjdk11:latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Run Instrumentation Action
        id: test-action
        uses: ./
        with:
          languages: java
          service-name: my-service
          api-key: "dummy"

      - name: Check If Java Tracing Works
        run: |
          LOG_FILE=java-output.log
          TRACER_INIT_LOG="CI Visibility settings"
          
          java -version 2>&1 | tee $LOG_FILE
          grep -q "$TRACER_INIT_LOG" $LOG_FILE || { echo "Error: Output does not contain tracer initialisation log: $TRACER_INIT_LOG"; exit 1; }
